import Link from "next/link";
import { ArrowRight, ArrowLeft } from "lucide-react";
import { SectionReveal } from "@/components/section-reveal";

const exportMarkets = [
  {
    region: "Middle East & GCC",
    countries: "UAE, Saudi Arabia, Qatar, Oman, Kuwait, Bahrain",
    desc: "Halal-certified softgel capsule exports to GCC nations — the fastest-growing nutraceutical import market in West Asia. We provide Halal certification, Arabic labeling support, and regulatory documentation aligned with Gulf Standards Organization (GSO) requirements.",
  },
  {
    region: "Africa",
    countries: "Kenya, Nigeria, Ghana, Tanzania, South Africa, Ethiopia",
    desc: "Sub-Saharan and East African markets represent significant demand for affordable, quality-certified nutraceutical softgels. We supply Vitamin D3, Omega-3, and multivitamin formulations with WHO-GMP documentation accepted by national drug authorities across the continent.",
  },
  {
    region: "Southeast Asia",
    countries: "Malaysia, Indonesia, Philippines, Vietnam, Cambodia, Myanmar",
    desc: "ASEAN countries with growing nutraceutical consumption. We support Halal certification for Malaysia and Indonesia, FDA registration for the Philippines, and country-specific import documentation for each market.",
  },
  {
    region: "Central Asia & CIS",
    countries: "Kazakhstan, Uzbekistan, Tajikistan",
    desc: "CIS nations with emerging nutraceutical distribution networks. We provide export documentation compatible with EAEU (Eurasian Economic Union) technical regulations and Russian-language COA translations on request.",
  },
  {
    region: "Latin America",
    countries: "Mexico, Colombia, Bolivia",
    desc: "Growing health supplement markets in Central and South America. We support COFEPRIS-aligned documentation for Mexico and INVIMA documentation for Colombia, with Spanish-language labeling support.",
  },
  {
    region: "South Asia",
    countries: "Nepal, Sri Lanka, Bangladesh",
    desc: "Neighboring markets with established trade corridors from India. Shorter transit times, competitive landed costs, and regulatory familiarity make these markets well-suited for Indian-manufactured softgel capsules.",
  },
];

const exportDocuments = [
  {
    title: "Certificate of Analysis (COA)",
    desc: "Per-batch analytical report covering identity, assay, dissolution, microbial limits, heavy metals, and physical specifications. Generated by our in-house QC lab for every production batch.",
  },
  {
    title: "Free Sale Certificate",
    desc: "Government-issued certificate confirming that the product is freely sold in India — required by most importing countries for nutraceutical registration and customs clearance.",
  },
  {
    title: "WHO-GMP Certificate",
    desc: "World Health Organization Good Manufacturing Practice certification for our Jind, Haryana facility — recognized by regulatory authorities across Africa, Asia, Latin America, and the Middle East.",
  },
  {
    title: "Halal Certificate",
    desc: "Halal certification covering gelatin sourcing, manufacturing processes, and facility hygiene — mandatory for import into GCC countries, Malaysia, Indonesia, and other Muslim-majority markets.",
  },
  {
    title: "Ingredient & Composition Declarations",
    desc: "Full ingredient declarations, nutritional information panels, and allergen statements formatted per importing country requirements. Multi-language support available.",
  },
  {
    title: "Country-Specific Regulatory Paperwork",
    desc: "Product dossiers, stability data, label mock-ups, and registration support documents tailored to each destination country's drug authority or food safety regulator.",
  },
  {
    title: "Export Packaging Specifications",
    desc: "Detailed packaging specifications including primary pack (blister/bottle), secondary cartons, shipper dimensions, weight, and palletization — formatted for freight forwarder and customs broker requirements.",
  },
];

const whyExportFromIndia = [
  {
    title: "Cost advantage without quality compromise",
    desc: "Indian nutraceutical manufacturing offers 40-60% cost savings versus European or US production — driven by lower raw material costs, competitive labor, and established pharmaceutical supply chains. Our WHO-GMP certification ensures quality systems match international standards.",
  },
  {
    title: "WHO-GMP certified facility",
    desc: "Our Jind, Haryana facility holds WHO-GMP certification — the international standard recognized by regulatory authorities across Africa, Middle East, Southeast Asia, and Latin America for pharmaceutical and nutraceutical imports.",
  },
  {
    title: "Halal & multi-certification readiness",
    desc: "FSSAI, GMP, HACCP, Halal, and WHO-GMP certifications on a single site. This multi-certification eliminates the need for buyers to source from multiple suppliers for different market requirements.",
  },
  {
    title: "Skilled manufacturing workforce",
    desc: "90%+ women workforce trained on-site in precision encapsulation, quality control, blister packing, and export dispatch protocols. Consistent batch quality across production runs.",
  },
  {
    title: "Strategic port connectivity",
    desc: "Our facility is ~1,200km from JNPT (Nhava Sheva, Mumbai) and ~1,100km from Mundra port — India's two largest container ports for west-coast export. Air freight routes via Delhi IGI airport (~150km). This connectivity supports 4-6 week sea freight to most African and Middle Eastern ports.",
  },
];

const exportProducts = [
  { name: "Cholecalciferol (Vitamin D3) 60,000 IU", category: "Bone & immunity", href: "/products/" },
  { name: "Calcitriol + Calcium Carbonate + Vitamin K2-7", category: "Bone health", href: "/products/" },
  { name: "Omega-3 Fatty Acids + Vitamin E", category: "Cardiovascular", href: "/products/" },
  { name: "Krill Oil Softgel Capsules", category: "Cardiovascular", href: "/products/" },
  { name: "Ginseng + Astaxanthin Multivitamin", category: "General wellness", href: "/products/" },
  { name: "Glutathione + ALA + Grape Seed Extract", category: "Antioxidant", href: "/products/" },
  { name: "Lycopene + Grape Seed Multivitamin", category: "Antioxidant", href: "/products/" },
  { name: "Isoflavones + Calcium + D3 (Women's Health)", category: "Women's health", href: "/products/" },
  { name: "Ginkgo Biloba + Tribulus Terrestris", category: "Men's vitality", href: "/products/" },
  { name: "Nigella Sativa (Kalonji) Oil", category: "Traditional wellness", href: "/products/" },
];

const faqs = [
  {
    q: "What countries do you export softgel capsules to?",
    a: "Admetus Lifesciences exports nutraceutical softgel capsules to 25+ countries across six regions: Middle East & GCC (UAE, Saudi Arabia, Qatar, Oman, Kuwait, Bahrain), Africa (Kenya, Nigeria, Ghana, Tanzania, South Africa, Ethiopia), Southeast Asia (Malaysia, Indonesia, Philippines, Vietnam, Cambodia, Myanmar), Central Asia & CIS (Kazakhstan, Uzbekistan, Tajikistan), Latin America (Mexico, Colombia, Bolivia), and South Asia (Nepal, Sri Lanka, Bangladesh). We continuously expand our export footprint based on buyer demand and regulatory approvals.",
  },
  {
    q: "What export documentation do you provide?",
    a: "We provide comprehensive export documentation for every shipment: Certificate of Analysis (COA) per batch, Free Sale Certificate, WHO-GMP certificate, Halal certificate, ingredient and composition declarations, country-specific regulatory paperwork (product dossiers, stability data, label mock-ups), and detailed export packaging specifications. All documents are prepared in-house and can be customized for specific country requirements.",
  },
  {
    q: "Are your softgel capsules Halal certified for GCC import?",
    a: "Yes. Our manufacturing facility holds Halal certification covering gelatin sourcing, production processes, and facility hygiene protocols. This certification is specifically required for import into UAE, Saudi Arabia, Qatar, Oman, Kuwait, Bahrain, Malaysia, Indonesia, and other Muslim-majority markets. Certificate copies are provided with every GCC-bound shipment.",
  },
  {
    q: "What is the minimum order quantity for export orders?",
    a: "Export MOQs are flexible and depend on the formulation, packaging format, and destination country. We support both pilot orders for market testing and full-scale production runs for established distributors. Specific MOQ and pricing for your order configuration is confirmed within 48 hours of inquiry at team@admetuslifesciences.com.",
  },
  {
    q: "What is the typical lead time for export softgel orders?",
    a: "Standard export lead time is 4-6 weeks from order confirmation to dispatch — covering raw material procurement, encapsulation, QC testing, packaging, and export documentation preparation. Sea freight transit adds 2-4 weeks to African and Middle Eastern ports, 1-3 weeks to Southeast Asian ports. Air freight via Delhi is available for urgent orders at additional cost.",
  },
  {
    q: "Can you provide private label softgel capsules for export?",
    a: "Yes. We offer full private-label export manufacturing — your brand identity on our formulations. This includes custom label design support, brand-specific packaging, and all export documentation under your company name. See our private label service page for the complete process, or contact us directly for export-specific private label pricing.",
  },
  {
    q: "What packaging options are available for export shipments?",
    a: "Export packaging options include: ALU-ALU blister packs (10s, 15s, 30s per strip), PVC/PVDC blister packs, HDPE bottles (30, 60, 90, 120 count), bulk drums for repackaging at destination, and custom retail-ready packaging. All export packaging meets ISTA transit testing standards. Shipper cartons are designed for standard pallet configurations (Euro or US).",
  },
  {
    q: "How do you handle international shipping and logistics?",
    a: "We support both FOB (Free on Board) and CIF (Cost, Insurance, Freight) shipping terms. Sea freight routes via JNPT (Mumbai) and Mundra port for west-coast destinations; air freight via Delhi IGI airport for time-sensitive orders. We coordinate with buyer-nominated freight forwarders or can arrange logistics through our established shipping partners. Full container loads (FCL) and less-than-container loads (LCL) are both supported.",
  },
];

const breadcrumbJsonLd = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    {
      "@type": "ListItem",
      position: 1,
      name: "Home",
      item: "https://www.admetuslifesciences.com/",
    },
    {
      "@type": "ListItem",
      position: 2,
      name: "Softgel Capsule Exporter India",
      item: "https://www.admetuslifesciences.com/softgel-capsule-exporter-india/",
    },
  ],
};

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqs.map((f) => ({
    "@type": "Question",
    name: f.q,
    acceptedAnswer: { "@type": "Answer", text: f.a },
  })),
};

export default function ExporterIndiaPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />

      {/* Hero */}
      <section className="relative min-h-[55vh] flex items-end pt-24 pb-12 overflow-hidden">
        <img
          src="/images/facility/dispatch-area.jpg"
          alt="Export dispatch area at Admetus Lifesciences — softgel capsule export packaging and logistics from India"
          className="absolute inset-0 w-full h-full object-cover"
          width={1920}
          height={1080}
          loading="eager"
        />
        <div className="absolute inset-0" style={{ background: "linear-gradient(to top, var(--hero-overlay-bottom), var(--hero-overlay-mid) 50%, var(--hero-overlay-top))" }} />
        <div className="absolute inset-0" style={{ background: "linear-gradient(135deg, rgba(200,169,81,0.04), transparent 60%)" }} />
        <div className="relative mx-auto max-w-[var(--container-max)] w-full px-[var(--gutter)]">
          <Link
            href="/"
            className="inline-flex items-center gap-2 py-2 label-text text-[var(--text-muted)] hover:text-[var(--gold)] transition-colors duration-200 mb-4"
          >
            <ArrowLeft size={13} />
            Home
          </Link>
          <span className="label-text text-[var(--gold)]">India  ·  Global Export</span>
          <h1 className="mt-3 display-section text-[var(--hero-text)]">
            SOFTGEL CAPSULE<br />EXPORTER FROM&nbsp;INDIA
          </h1>
          <div className="gold-rule w-16 mt-4 mb-4" />
          <p className="body-large text-[var(--text-cream)] max-w-[58ch]">
            WHO-GMP certified nutraceutical &amp; Ayurvedic softgel capsule exporter and bulk supplier — serving
            distributors and importers across Africa, Middle East, Southeast Asia,
            Latin America, and CIS countries with full export&nbsp;documentation.
          </p>
        </div>
      </section>

      {/* Intro / context */}
      <section className="py-16">
        <div className="mx-auto max-w-[var(--container-max)] px-[var(--gutter)]">
          <SectionReveal>
            <div className="max-w-[68ch] space-y-5">
              <p className="body-text text-[var(--text-cream)]" style={{ fontSize: "0.9375rem", lineHeight: 1.65 }}>
                Admetus Lifesciences is a <strong>softgel capsule exporter from India</strong>,
                manufacturing and supplying nutraceutical soft gelatin capsules to international
                buyers across 25+ countries. Our facility in{" "}
                <strong>Village Anta, Tehsil Safidon, District Jind, Haryana 126112</strong>{" "}
                holds WHO-GMP, FSSAI, GMP, HACCP, and Halal certifications — the complete
                certification stack required for pharmaceutical and nutraceutical exports
                to regulated international markets.
              </p>
              <p className="body-text text-[var(--text-cream)]" style={{ fontSize: "0.9375rem", lineHeight: 1.65 }}>
                As a bulk softgel capsule supplier from India, we handle end-to-end export
                operations — from formulation and encapsulation through quality testing,
                export packaging, regulatory documentation, and dispatch coordination with
                international freight forwarders. Every export shipment includes a Certificate
                of Analysis (COA), Free Sale Certificate, and country-specific regulatory
                paperwork.
              </p>
            </div>
          </SectionReveal>
        </div>
      </section>

      {/* Export Markets */}
      <section className="py-20 bg-[var(--bg-charcoal)] border-y border-[var(--border-subtle)]">
        <div className="mx-auto max-w-[var(--container-max)] px-[var(--gutter)]">
          <SectionReveal>
            <span className="label-text text-[var(--gold)]">Export Markets</span>
            <h2 className="mt-3 display-section text-[var(--foreground)] mb-4" style={{ fontSize: "clamp(1.75rem, 3.5vw, 2.5rem)" }}>
              REGIONS &amp; COUNTRIES WE&nbsp;SERVE
            </h2>
            <div className="gold-rule w-16 mb-10" />
          </SectionReveal>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-x-16 gap-y-0">
            {exportMarkets.map((market, i) => (
              <SectionReveal key={market.region} delay={i * 0.04}>
                <div className="py-6 border-t border-[var(--border-subtle)] flex items-start gap-5">
                  <span className="mono-text text-[0.6875rem] font-bold text-[var(--gold)] shrink-0 mt-1">
                    {String(i + 1).padStart(2, "0")}
                  </span>
                  <div>
                    <h3 className="heading-2 text-[var(--foreground)]" style={{ fontSize: "clamp(1.125rem, 2vw, 1.375rem)" }}>
                      {market.region}
                    </h3>
                    <p className="mt-1 mono-text text-[0.75rem] text-[var(--gold)]">
                      {market.countries}
                    </p>
                    <p className="mt-2 body-text text-[var(--text-muted)] max-w-[58ch]">{market.desc}</p>
                  </div>
                </div>
              </SectionReveal>
            ))}
          </div>
        </div>
      </section>

      {/* Export Documentation */}
      <section className="py-20">
        <div className="mx-auto max-w-[var(--container-max)] px-[var(--gutter)]">
          <div className="grid grid-cols-1 lg:grid-cols-[1fr_1.4fr] gap-10 lg:gap-16 items-start">
            <SectionReveal>
              <div>
                <span className="label-text text-[var(--gold)]">Export Documentation</span>
                <h2 className="mt-3 display-section text-[var(--foreground)] mb-4" style={{ fontSize: "clamp(1.75rem, 3.5vw, 2.5rem)" }}>
                  DOCUMENTS WE&nbsp;PROVIDE
                </h2>
                <div className="gold-rule w-12 mb-6" />
                <p className="body-text text-[var(--text-cream)] max-w-[52ch]" style={{ fontSize: "0.9375rem", lineHeight: 1.65 }}>
                  Every export shipment from Admetus Lifesciences is accompanied by
                  comprehensive documentation — prepared in-house and customized
                  for each destination country&apos;s regulatory&nbsp;requirements.
                </p>
              </div>
            </SectionReveal>

            <SectionReveal delay={0.1}>
              <ol className="space-y-4">
                {exportDocuments.map((doc, i) => (
                  <li key={doc.title} className="flex items-start gap-4 body-text text-[var(--text-cream)]">
                    <span className="shrink-0 mono-text text-[0.6875rem] font-bold text-[var(--gold)] mt-1.5">
                      {String(i + 1).padStart(2, "0")}
                    </span>
                    <div>
                      <h3 className="heading-2 text-[var(--foreground)]" style={{ fontSize: "clamp(1rem, 1.6vw, 1.125rem)" }}>{doc.title}</h3>
                      <p className="mt-1 body-text text-[var(--text-muted)] max-w-[58ch] !text-[0.9375rem]">{doc.desc}</p>
                    </div>
                  </li>
                ))}
              </ol>
            </SectionReveal>
          </div>
        </div>
      </section>

      {/* Why Export From India */}
      <section className="py-20 bg-[var(--bg-charcoal)] border-y border-[var(--border-subtle)]">
        <div className="mx-auto max-w-[var(--container-max)] px-[var(--gutter)]">
          <SectionReveal>
            <span className="label-text text-[var(--gold)]">Why India</span>
            <h2 className="mt-3 display-section text-[var(--foreground)] mb-4" style={{ fontSize: "clamp(1.75rem, 3.5vw, 2.5rem)" }}>
              WHY EXPORT SOFTGEL CAPSULES FROM&nbsp;INDIA
            </h2>
            <div className="gold-rule w-16 mb-10" />
          </SectionReveal>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-x-16 gap-y-0">
            {whyExportFromIndia.map((item, i) => (
              <SectionReveal key={item.title} delay={i * 0.04}>
                <div className="py-6 border-t border-[var(--border-subtle)] flex items-start gap-5">
                  <span className="mono-text text-[0.6875rem] font-bold text-[var(--gold)] shrink-0 mt-1">
                    {String(i + 1).padStart(2, "0")}
                  </span>
                  <div>
                    <h3 className="heading-2 text-[var(--foreground)]" style={{ fontSize: "clamp(1.125rem, 2vw, 1.375rem)" }}>{item.title}</h3>
                    <p className="mt-1.5 body-text text-[var(--text-muted)] max-w-[58ch]">{item.desc}</p>
                  </div>
                </div>
              </SectionReveal>
            ))}
          </div>
        </div>
      </section>

      {/* Products Available for Export */}
      <section className="py-20">
        <div className="mx-auto max-w-[var(--container-max)] px-[var(--gutter)]">
          <SectionReveal>
            <span className="label-text text-[var(--gold)]">Export Product Range</span>
            <h2 className="mt-3 display-section text-[var(--foreground)] mb-4" style={{ fontSize: "clamp(1.75rem, 3.5vw, 2.5rem)" }}>
              SOFTGEL FORMULATIONS AVAILABLE FOR&nbsp;EXPORT
            </h2>
            <div className="gold-rule w-16 mb-6" />
            <p className="body-text text-[var(--text-cream)] max-w-[68ch] mb-10" style={{ fontSize: "0.9375rem", lineHeight: 1.65 }}>
              All formulations are manufactured at our WHO-GMP certified Jind facility
              and available in export packaging — ALU-ALU blister packs, HDPE bottles,
              or bulk drums for repackaging at destination. Custom formulations
              developed on&nbsp;request.
            </p>
          </SectionReveal>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-px bg-[var(--border-subtle)] border border-[var(--border-subtle)]">
            {exportProducts.map((product, i) => (
              <SectionReveal key={product.name} delay={i * 0.03}>
                <div className="p-5 bg-[var(--background)] flex items-start gap-4">
                  <span className="mono-text text-[0.6875rem] font-bold text-[var(--gold)] shrink-0 mt-1">
                    {String(i + 1).padStart(2, "0")}
                  </span>
                  <div>
                    <Link
                      href={product.href}
                      className="heading-2 text-[var(--foreground)] hover:text-[var(--gold)] transition-colors duration-200"
                      style={{ fontSize: "clamp(0.9375rem, 1.5vw, 1.0625rem)" }}
                    >
                      {product.name}
                    </Link>
                    <span className="block mt-1 mono-text text-[0.6875rem] text-[var(--text-muted)] uppercase tracking-[0.1em]">
                      {product.category}
                    </span>
                  </div>
                </div>
              </SectionReveal>
            ))}
          </div>

          <SectionReveal delay={0.2}>
            <div className="mt-8">
              <Link
                href="/products/"
                className="inline-flex items-center gap-2 label-text text-[var(--gold)] hover:text-[var(--gold-light)] transition-colors duration-200"
              >
                View full product catalogue
                <ArrowRight size={13} />
              </Link>
            </div>
          </SectionReveal>
        </div>
      </section>

      {/* FAQ */}
      <section className="py-20 bg-[var(--bg-charcoal)] border-y border-[var(--border-subtle)]">
        <div className="mx-auto max-w-[var(--container-max)] px-[var(--gutter)]">
          <SectionReveal>
            <span className="label-text text-[var(--gold)]">Frequently Asked</span>
            <h2 className="mt-3 display-section text-[var(--foreground)] mb-4">
              EXPORT Q&amp;A
            </h2>
            <div className="gold-rule w-16 mb-10" />
          </SectionReveal>

          <div className="space-y-0">
            {faqs.map((faq, i) => (
              <SectionReveal key={faq.q} delay={i * 0.03}>
                <details className="group py-6 border-t border-[var(--border-subtle)] last:border-b">
                  <summary className="flex items-start gap-5 cursor-pointer list-none">
                    <span className="mono-text text-[0.6875rem] font-bold text-[var(--gold)] shrink-0 mt-1">
                      {String(i + 1).padStart(2, "0")}
                    </span>
                    <h3
                      className="heading-2 text-[var(--foreground)] group-hover:text-[var(--gold)] transition-colors duration-200"
                      style={{ fontSize: "clamp(1rem, 1.6vw, 1.25rem)" }}
                    >
                      {faq.q}
                    </h3>
                  </summary>
                  <p className="mt-4 ml-12 body-text text-[var(--text-muted)] max-w-[68ch]">
                    {faq.a}
                  </p>
                </details>
              </SectionReveal>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20">
        <div className="mx-auto max-w-[var(--container-max)] px-[var(--gutter)]">
          <SectionReveal>
            <h2 className="display-section text-[var(--foreground)]">
              START EXPORTING WITH&nbsp;US
            </h2>
            <div className="gold-rule w-12 mt-4 mb-4" />
            <p className="body-text text-[var(--text-muted)] max-w-[58ch]">
              Request an export quote, discuss MOQs for your target market, or schedule
              a facility audit. We respond to export inquiries within 48&nbsp;hours.
            </p>
            <div className="mt-8 flex flex-wrap items-center gap-4">
              <Link
                href="/contact/"
                className="inline-flex items-center gap-3 px-7 py-3 active:scale-[0.98] active:opacity-90 text-[0.6875rem] font-bold tracking-[0.14em] uppercase text-[var(--bg-black)] bg-[var(--gold)] hover:bg-[var(--gold-light)] transition-colors duration-200"
                style={{ fontFamily: "var(--font-display)" }}
              >
                Request Export Quote
                <ArrowRight size={14} />
              </Link>
              <Link
                href="/products/"
                className="inline-flex items-center gap-3 px-7 py-3 active:scale-[0.98] active:opacity-90 text-[0.6875rem] font-bold tracking-[0.14em] uppercase text-[var(--foreground)] border border-[var(--border-subtle)] hover:border-[var(--gold)] hover:text-[var(--gold)] transition-colors duration-200"
                style={{ fontFamily: "var(--font-display)" }}
              >
                Browse Products
                <ArrowRight size={14} />
              </Link>
            </div>
          </SectionReveal>
        </div>
      </section>
    </>
  );
}
